name: draft
on:
  pull_request:
    types: 
      - converted_to_draft
    branches:
      - future
jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
