name: fb notification
on: [push]

jobs:
  send_notifivation:
    runs-on: ubuntu-latest 
    steps:
    - name: send custom message
      uses: appleboy/facebook-action@master
      with:
        fb_page_token: ${{ secrets.FB_PAGE_TOKEN }}
        fb_verify_token: ${{ secrets.FB_VERIFY_TOKEN }}
        to: ${{ secrets.FB_TO }}
        args: The ${{ github.event_name }} event triggered first step. 
