name: get-errors
on:
  pull_request:
    types: 
      - opened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
           ref: ${{github.event.pull_request.head.ref}}
      - name: echo-branch
        run: | 
          echo  ${{ github.event.pull_request.head.ref }}

      
