name: get-errors
on:
  push:

jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        continue-on-error: true
        with:
            node-version: 16
            cache: 'npm'
      - run: npm ci
        continue-on-error: true
      - run: npm test
        continue-on-error: true
      - name: any
        run: |
          echo "hello world"
          ls
      - name: any1
        run: |
          cat a.txt
        continue-on-error: true
          
      - name: print-steps
        env:
          STEPS_CONTEXT: ${{ toJson(steps.any1) }}
        run: echo "$STEPS_CONTEXT"
