name: get-errors
on:
  push:

jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: any
        run: |
          echo "hello world"
          ls
      - name: any1
        run: |
          cat a.txt
          
      - name: print-steps
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
