name: static-tests
on:
  pull_request: 
    types:
      - ready_for_review    
  push:
    
jobs:
  static-tests:
    name: Run in ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Get information about pull requests
      id: PR 
      uses: 8BitJonny/gh-get-current-pr@2.1.1
    - name: Run static tests
      if: fromJSON(steps.PR.outputs.pr).draft  == false || ${{ github.event.action }}  == "ready_for_review"
      id: pytest
      run: |
        pip3 install -r requirement.txt
        pytest test-app.py
      
        
        
